### ISSUE TITLE
testing in windows

### ISSUE THREAD

**Issue by jorgepz** [JuliaReach/SetPropagation-FEM-Examples#14]

**Comment by dfcaporale** [comment]
It ran in my Windows machine without the LONG flag. So now, I'm testing with the LONG flag.

**Comment by jorgepz** [comment]
ERROR: LoadError: ArgumentError: Package IntervalArithmetic not found in current path:                                  - Run `import Pkg; Pkg.add("IntervalArithmetic")` to install the IntervalArithmetic package.                                                                                                                                                    Stacktrace:                                                                                                              [1] require(into::Module, mod::Symbol)                                                                                    @ Base .\loading.jl:967                                                                                               [2] include                                                                                                               @ .\client.jl:451 [inlined]                                                                                           [3] main()                                                                                                                @ Main C:\Users\jor\Downloads\SetPropagation-FEM-Examples-main\runall.jl:58                                           [4] top-level scope                                                                                                       @ C:\Users\jor\Downloads\SetPropagation-FEM-Examples-main\runall.jl:73                                                [5] include(fname::String)                                                                                                @ Base.MainInclude .\client.jl:451                                                                                    [6] top-level scope                                                                                                       @ REPL[3]:1                                                                                                          in expression starting at C:\Users\jor\Downloads\SetPropagation-FEM-Examples-main\examples\Heat1D\Heat1D_TempGradient.jl:9                                                                                                                      in expression starting at C:\Users\jor\Downloads\SetPropagation-FEM-Examples-main\runall.jl:73                                                                                                                                                  julia

**Comment by jorgepz** [comment]
`Finished running benchmarks.` ok after doing the modification in #15
